import {
  useEffect,
  useMemo,
  useRef,
  useState,
} from "react";

import type {
  CSSProperties,
  MouseEvent,
} from "react";

import "./LibraryView.css";

type ViewPhase =
  | "home"
  | "entering-conversations"
  | "conversations"
  | "leaving-conversations"
  | "entering-library"
  | "library"
  | "leaving-library";

type ArtifactType =
  | "image"
  | "video"
  | "pdf"
  | "document"
  | "audio"
  | "link"
  | "archive"
  | "unknown";

type ArtifactStatus =
  | "Available"
  | "Duplicate"
  | "Link error";

type Artifact = {
  id: string;
  name: string;
  type: ArtifactType;
  extension: string;
  dateGroup:
    | "Today"
    | "Yesterday"
    | "This week"
    | "This month"
    | "Older";
  dateValue: number;
  dateText: string;
  time: string;
  sizeBytes: number;
  sizeText: string;
  source: string;
  status: ArtifactStatus;
  pathOrUrl: string;
  duplicateOf?: string;
  tone:
    | "cyan"
    | "indigo"
    | "violet"
    | "neutral";
};

type SortMode =
  | "newest"
  | "oldest"
  | "az"
  | "za"
  | "type"
  | "size";

type FilterMode =
  | "all"
  | ArtifactType;

type ViewMode =
  | "compact"
  | "gallery";

type LibraryViewProps = {
  phase: ViewPhase;
  onClose: () => void;
};

type MenuState = {
  x: number;
  y: number;
  artifactId: string;
};

type Particle = {
  id: number;
  originX: number;
  originY: number;
  radiusX: number;
  radiusY: number;
  phase: number;
  speed: number;
  size: number;
  alpha: number;
  tone:
    | "cyan"
    | "indigo"
    | "white";
};

const MAX_DPR = 1;
const TRANSITION_MS = 1120;
const PARTICLE_COUNT = 420;

const initialArtifacts: Artifact[] = [
  {
    id: "img-1",
    name: "Qronos_UI_Preview.png",
    type: "image",
    extension: "PNG",
    dateGroup: "Today",
    dateValue: 202608261912,
    dateText: "26 Aug 2026",
    time: "19:12",
    sizeBytes: 4_200_000,
    sizeText: "4.2 MB",
    source: "Generated by Qronos",
    status: "Available",
    pathOrUrl: "E:\\Qronos Library\\Qronos_UI_Preview.png",
    tone: "cyan",
  },
  {
    id: "pdf-1",
    name: "Qronos_UI_Checkpoint.pdf",
    type: "pdf",
    extension: "PDF",
    dateGroup: "Today",
    dateValue: 202608261908,
    dateText: "26 Aug 2026",
    time: "19:08",
    sizeBytes: 2_400_000,
    sizeText: "2.4 MB",
    source: "Generated by Qronos",
    status: "Available",
    pathOrUrl: "E:\\Qronos Library\\Qronos_UI_Checkpoint.pdf",
    tone: "indigo",
  },
  {
    id: "img-dup",
    name: "Qronos_UI_Preview_copy.png",
    type: "image",
    extension: "PNG",
    dateGroup: "Today",
    dateValue: 202608261915,
    dateText: "26 Aug 2026",
    time: "19:15",
    sizeBytes: 4_200_000,
    sizeText: "4.2 MB",
    source: "Generated by Qronos",
    status: "Duplicate",
    duplicateOf: "Qronos_UI_Preview.png",
    pathOrUrl: "E:\\Qronos Library\\Qronos_UI_Preview_copy.png",
    tone: "cyan",
  },
  {
    id: "video-1",
    name: "orb_transition_reference.mp4",
    type: "video",
    extension: "MP4",
    dateGroup: "Yesterday",
    dateValue: 202608252105,
    dateText: "25 Aug 2026",
    time: "21:05",
    sizeBytes: 184_000_000,
    sizeText: "184 MB",
    source: "Downloaded by Qronos",
    status: "Available",
    pathOrUrl: "E:\\Qronos Library\\orb_transition_reference.mp4",
    tone: "violet",
  },
  {
    id: "doc-1",
    name: "Architecture_Notes.docx",
    type: "document",
    extension: "DOCX",
    dateGroup: "This week",
    dateValue: 202608241522,
    dateText: "24 Aug 2026",
    time: "15:22",
    sizeBytes: 780_000,
    sizeText: "780 KB",
    source: "Exported by Qronos",
    status: "Available",
    pathOrUrl: "E:\\Qronos Library\\Architecture_Notes.docx",
    tone: "neutral",
  },
  {
    id: "audio-1",
    name: "wakeword_sample.wav",
    type: "audio",
    extension: "WAV",
    dateGroup: "This week",
    dateValue: 202608231117,
    dateText: "23 Aug 2026",
    time: "11:17",
    sizeBytes: 9_600_000,
    sizeText: "9.6 MB",
    source: "Captured by Qronos",
    status: "Available",
    pathOrUrl: "E:\\Qronos Library\\wakeword_sample.wav",
    tone: "cyan",
  },
  {
    id: "link-1",
    name: "qronos-agent",
    type: "link",
    extension: "LINK",
    dateGroup: "This week",
    dateValue: 202608221938,
    dateText: "22 Aug 2026",
    time: "19:38",
    sizeBytes: 0,
    sizeText: "WEB",
    source: "Saved by Qronos",
    status: "Available",
    pathOrUrl: "https://github.com/mkhphoto46-rgb/qronos-agent",
    tone: "indigo",
  },
  {
    id: "zip-1",
    name: "qronos_export.zip",
    type: "archive",
    extension: "ZIP",
    dateGroup: "This month",
    dateValue: 202608171024,
    dateText: "17 Aug 2026",
    time: "10:24",
    sizeBytes: 126_000_000,
    sizeText: "126 MB",
    source: "Exported by Qronos",
    status: "Available",
    pathOrUrl: "E:\\Qronos Library\\qronos_export.zip",
    tone: "neutral",
  },
  {
    id: "link-bad",
    name: "expired_reference",
    type: "link",
    extension: "LINK",
    dateGroup: "Older",
    dateValue: 202607101320,
    dateText: "10 Jul 2026",
    time: "13:20",
    sizeBytes: 0,
    sizeText: "WEB",
    source: "Saved by Qronos",
    status: "Link error",
    pathOrUrl: "https://example.invalid/qronos-reference",
    tone: "neutral",
  },
  {
    id: "unknown-1",
    name: "model_blob.qrx",
    type: "unknown",
    extension: "QRX",
    dateGroup: "Older",
    dateValue: 202606291041,
    dateText: "29 Jun 2026",
    time: "10:41",
    sizeBytes: 31_000_000,
    sizeText: "31 MB",
    source: "Downloaded by Qronos",
    status: "Available",
    pathOrUrl: "E:\\Qronos Library\\model_blob.qrx",
    tone: "neutral",
  },
];

function clamp01(value: number) {
  return Math.max(0, Math.min(1, value));
}

function smootherStep(value: number) {
  const t = clamp01(value);
  return t * t * t * (t * (t * 6 - 15) + 10);
}

function seededRandom(seed: number) {
  let value = seed >>> 0;

  return () => {
    value = (value * 1664525 + 1013904223) >>> 0;
    return value / 4294967296;
  };
}

function buildParticles() {
  const random = seededRandom(772451);

  return Array.from(
    { length: PARTICLE_COUNT },
    (_, index) => ({
      id: index,
      originX: 0.86 + random() * 0.1,
      originY: 0.12 + random() * 0.76,
      radiusX: 0.04 + random() * 0.18,
      radiusY: 0.025 + random() * 0.12,
      phase: random() * Math.PI * 2,
      speed: 0.3 + random() * 0.8,
      size:
        index % 7 === 0
          ? 0.42 + random() * 0.55
          : 0.2 + random() * 0.38,
      alpha: 0.12 + random() * 0.4,
      tone:
        index % 13 === 0
          ? "white"
          : index % 4 === 0
            ? "indigo"
            : "cyan",
    } satisfies Particle),
  );
}

const particles = buildParticles();

function LibraryParticleCanvas({
  phase,
}: {
  phase: ViewPhase;
}) {
  const canvasRef = useRef<HTMLCanvasElement | null>(null);
  const phaseRef = useRef<ViewPhase>(phase);
  const phaseStartedRef = useRef(performance.now());

  useEffect(() => {
    phaseRef.current = phase;
    phaseStartedRef.current = performance.now();
  }, [phase]);

  useEffect(() => {
    const canvas = canvasRef.current;
    if (!canvas) return;

    const context = canvas.getContext("2d", { alpha: true });
    if (!context) return;

    let width = 1;
    let height = 1;
    let dpr = 1;
    let frame = 0;
    let visible = !document.hidden;

    const resize = () => {
      width = Math.max(1, window.innerWidth);
      height = Math.max(1, window.innerHeight);
      dpr = Math.min(window.devicePixelRatio || 1, MAX_DPR);

      canvas.width = Math.round(width * dpr);
      canvas.height = Math.round(height * dpr);
      canvas.style.width = `${width}px`;
      canvas.style.height = `${height}px`;

      context.setTransform(dpr, 0, 0, dpr, 0, 0);
    };

    resize();

    const handleResize = () => resize();
    const handleVisibility = () => {
      visible = !document.hidden;
    };

    window.addEventListener("resize", handleResize);
    document.addEventListener("visibilitychange", handleVisibility);

    const render = (timestamp: number) => {
      frame = window.requestAnimationFrame(render);
      if (!visible) return;

      context.clearRect(0, 0, width, height);

      const currentPhase = phaseRef.current;

      if (
        currentPhase === "home" ||
        currentPhase === "conversations" ||
        currentPhase === "entering-conversations" ||
        currentPhase === "leaving-conversations"
      ) {
        return;
      }

      const elapsed = timestamp - phaseStartedRef.current;
      let transition = 1;

      if (currentPhase === "entering-library") {
        transition = smootherStep(elapsed / TRANSITION_MS);
      } else if (currentPhase === "leaving-library") {
        transition = 1 - smootherStep(elapsed / TRANSITION_MS);
      }

      const time = timestamp * 0.001;

      for (const particle of particles) {
        const originX = particle.originX * width;
        const originY = particle.originY * height;

        const centerX =
          width * (0.47 + ((particle.id % 7) - 3) * 0.025);
        const centerY =
          height * (0.48 + ((particle.id % 9) - 4) * 0.016);

        const angle =
          particle.phase +
          time *
            particle.speed *
            (particle.id % 2 === 0 ? 1 : -1);

        const targetX =
          centerX +
          Math.cos(angle) * particle.radiusX * width;

        const targetY =
          centerY +
          Math.sin(angle * 1.14) * particle.radiusY * height;

        const controlX = width * (0.74 - particle.radiusX * 0.35);
        const controlY =
          height * (0.46 + Math.sin(particle.phase) * 0.18);

        const inv = 1 - transition;

        let x =
          inv * inv * originX +
          2 * inv * transition * controlX +
          transition * transition * targetX;

        let y =
          inv * inv * originY +
          2 * inv * transition * controlY +
          transition * transition * targetY;

        const travelEnvelope = Math.sin(transition * Math.PI);

        x +=
          Math.sin(particle.phase + transition * 7.2) *
          7 *
          travelEnvelope;

        y +=
          Math.cos(particle.phase * 1.4 + transition * 6.1) *
          5 *
          travelEnvelope;

        const alpha =
          particle.alpha *
          smootherStep(transition / 0.16) *
          (currentPhase === "library"
            ? 0.34 +
              ((Math.sin(time * (0.8 + particle.speed) + particle.phase) + 1) /
                2) *
                0.32
            : 0.76);

        if (alpha < 0.008) continue;

        context.globalAlpha = Math.min(1, alpha);
        context.fillStyle =
          particle.tone === "indigo"
            ? "rgba(102,126,255,1)"
            : particle.tone === "white"
              ? "rgba(242,252,255,1)"
              : "rgba(69,218,255,1)";

        context.beginPath();
        context.arc(x, y, particle.size, 0, Math.PI * 2);
        context.fill();
      }

      context.globalAlpha = 1;
    };

    frame = window.requestAnimationFrame(render);

    return () => {
      window.cancelAnimationFrame(frame);
      window.removeEventListener("resize", handleResize);
      document.removeEventListener("visibilitychange", handleVisibility);
    };
  }, []);

  return (
    <canvas
      ref={canvasRef}
      className="library-particle-canvas"
      aria-hidden="true"
    />
  );
}

function ArtifactIcon({
  type,
}: {
  type: ArtifactType;
}) {
  if (type === "image") {
    return (
      <svg viewBox="0 0 24 24" aria-hidden="true">
        <rect x="4" y="5" width="16" height="14" rx="2" />
        <circle cx="9" cy="10" r="1.5" />
        <path d="m6 17 4-4 3 3 2-2 3 3" />
      </svg>
    );
  }

  if (type === "video") {
    return (
      <svg viewBox="0 0 24 24" aria-hidden="true">
        <rect x="4" y="5" width="16" height="14" rx="2" />
        <path d="m10 9 5 3-5 3Z" />
      </svg>
    );
  }

  if (type === "pdf") {
    return (
      <svg viewBox="0 0 24 24" aria-hidden="true">
        <path d="M7 3h7l4 4v14H7Z" />
        <path d="M14 3v5h5" />
        <path d="M9 15h6M9 12h4" />
      </svg>
    );
  }

  if (type === "document") {
    return (
      <svg viewBox="0 0 24 24" aria-hidden="true">
        <rect x="5" y="3" width="14" height="18" rx="2" />
        <path d="M8 8h8M8 12h8M8 16h5" />
      </svg>
    );
  }

  if (type === "audio") {
    return (
      <svg viewBox="0 0 24 24" aria-hidden="true">
        <path d="M5 14v-4M8 17V7M11 15V9M14 19V5M17 15V9M20 13v-2" />
      </svg>
    );
  }

  if (type === "link") {
    return (
      <svg viewBox="0 0 24 24" aria-hidden="true">
        <path d="M9.5 14.5 14.5 9.5" />
        <path d="M7.2 16.8 5.7 18.3a3.3 3.3 0 0 1-4.7-4.7l3.5-3.5a3.3 3.3 0 0 1 4.7 0" />
        <path d="m16.8 7.2 1.5-1.5A3.3 3.3 0 1 1 23 10.4l-3.5 3.5a3.3 3.3 0 0 1-4.7 0" />
      </svg>
    );
  }

  if (type === "archive") {
    return (
      <svg viewBox="0 0 24 24" aria-hidden="true">
        <path d="M5 6h14v14H5Z" />
        <path d="M7 3h10v3H7ZM12 8v8M10 10h4M10 13h4" />
      </svg>
    );
  }

  return (
    <svg viewBox="0 0 24 24" aria-hidden="true">
      <path d="M7 3h7l4 4v14H7Z" />
      <path d="M14 3v5h5" />
      <path d="M10 12.5h4M12 10.5v4" />
    </svg>
  );
}

function LibraryView({
  phase,
  onClose,
}: LibraryViewProps) {
  const [artifacts, setArtifacts] = useState<Artifact[]>(initialArtifacts);
  const [selectedId, setSelectedId] = useState(initialArtifacts[0].id);
  const [search, setSearch] = useState("");
  const [filter, setFilter] = useState<FilterMode>("all");
  const [sort, setSort] = useState<SortMode>("newest");
  const [viewMode, setViewMode] = useState<ViewMode>("compact");
  const [menu, setMenu] = useState<MenuState | null>(null);
  const [renamingId, setRenamingId] = useState<string | null>(null);
  const [renameValue, setRenameValue] = useState("");
  const [toast, setToast] = useState<string | null>(null);

  const renameRef = useRef<HTMLInputElement | null>(null);
  const toastTimerRef = useRef<number | null>(null);

  const visible =
    phase === "entering-library" ||
    phase === "library" ||
    phase === "leaving-library";

  const phaseClass =
    phase === "entering-library"
      ? "library-view-entering"
      : phase === "leaving-library"
        ? "library-view-leaving"
        : phase === "library"
          ? "library-view-visible"
          : "";

  const showToast = (message: string) => {
    setToast(message);

    if (toastTimerRef.current !== null) {
      window.clearTimeout(toastTimerRef.current);
    }

    toastTimerRef.current = window.setTimeout(() => {
      setToast(null);
      toastTimerRef.current = null;
    }, 2200);
  };

  useEffect(() => {
    return () => {
      if (toastTimerRef.current !== null) {
        window.clearTimeout(toastTimerRef.current);
      }
    };
  }, []);

  useEffect(() => {
    if (renamingId && renameRef.current) {
      renameRef.current.focus();
      const input = renameRef.current;
      const dot = input.value.lastIndexOf(".");
      input.setSelectionRange(0, dot > 0 ? dot : input.value.length);
    }
  }, [renamingId]);

  useEffect(() => {
    const close = () => setMenu(null);
    window.addEventListener("click", close);
    window.addEventListener("blur", close);

    return () => {
      window.removeEventListener("click", close);
      window.removeEventListener("blur", close);
    };
  }, []);

  const filtered = useMemo(() => {
    const query = search.trim().toLowerCase();

    return artifacts
      .filter((artifact) => filter === "all" || artifact.type === filter)
      .filter(
        (artifact) =>
          !query ||
          artifact.name.toLowerCase().includes(query) ||
          artifact.extension.toLowerCase().includes(query) ||
          artifact.source.toLowerCase().includes(query),
      )
      .sort((a, b) => {
        if (sort === "newest") return b.dateValue - a.dateValue;
        if (sort === "oldest") return a.dateValue - b.dateValue;
        if (sort === "az") return a.name.localeCompare(b.name, "fa");
        if (sort === "za") return b.name.localeCompare(a.name, "fa");
        if (sort === "type") return a.type.localeCompare(b.type);
        return b.sizeBytes - a.sizeBytes;
      });
  }, [artifacts, filter, search, sort]);

  const groupOrder: Artifact["dateGroup"][] = [
    "Today",
    "Yesterday",
    "This week",
    "This month",
    "Older",
  ];

  const groups = useMemo(
    () =>
      groupOrder
        .map((label) => ({
          label,
          items: filtered.filter((artifact) => artifact.dateGroup === label),
        }))
        .filter((group) => group.items.length > 0),
    [filtered],
  );

  const selected =
    artifacts.find((artifact) => artifact.id === selectedId) ?? null;

  const duplicateCount = artifacts.filter(
    (artifact) => artifact.status === "Duplicate",
  ).length;

  const beginRename = (artifact: Artifact) => {
    setSelectedId(artifact.id);
    setRenamingId(artifact.id);
    setRenameValue(artifact.name);
    setMenu(null);
  };

  const commitRename = () => {
    if (!renamingId) return;

    const nextName = renameValue.trim();
    if (!nextName) {
      setRenamingId(null);
      return;
    }

    setArtifacts((current) =>
      current.map((artifact) =>
        artifact.id === renamingId
          ? { ...artifact, name: nextName }
          : artifact,
      ),
    );

    setRenamingId(null);
    showToast("Rename در Prototype انجام شد");
  };

  const removeArtifact = (artifact: Artifact, forever: boolean) => {
    if (forever) {
      const approved = window.confirm(
        `Delete forever?\n${artifact.name}\n\nاین عملیات در نسخه نهایی غیرقابل بازگشت خواهد بود.`,
      );

      if (!approved) return;
    }

    setArtifacts((current) =>
      current.filter((item) => item.id !== artifact.id),
    );

    if (selectedId === artifact.id) {
      const next = artifacts.find((item) => item.id !== artifact.id);
      setSelectedId(next?.id ?? "");
    }

    setMenu(null);
    showToast(
      forever
        ? "Delete forever — Prototype only"
        : "Moved to Windows Trash — Prototype only",
    );
  };

  const mockOpen = (artifact: Artifact) => {
    setSelectedId(artifact.id);
    showToast(
      artifact.type === "link"
        ? "Backend: Default Browser باز خواهد شد"
        : "Backend: Default App ویندوز باز خواهد شد",
    );
  };

  const openContextMenu = (
    event: MouseEvent<HTMLElement>,
    artifact: Artifact,
  ) => {
    event.preventDefault();
    event.stopPropagation();

    setSelectedId(artifact.id);

    const x = Math.min(event.clientX, window.innerWidth - 205);
    const y = Math.min(event.clientY, window.innerHeight - 300);

    setMenu({
      x: Math.max(10, x),
      y: Math.max(10, y),
      artifactId: artifact.id,
    });
  };

  return (
    <section
      className={`library-view ${phaseClass}`}
      aria-hidden={!visible}
      dir="rtl"
    >
      <LibraryParticleCanvas phase={phase} />

      <div className="library-storage-origin" aria-hidden="true">
        <span className="library-storage-origin-core" />
        <span className="library-storage-origin-ring library-storage-origin-ring-a" />
        <span className="library-storage-origin-ring library-storage-origin-ring-b" />
      </div>

      <div className="library-responsive-shell">
        <header className="library-header">
        <div className="library-heading">
          <span>QRONOS ARTIFACT ARCHIVE</span>
          <h1>کتابخانه</h1>
          <p>منابع ثبت‌شده توسط Qronos</p>
        </div>

        <div className="library-summary">
          <strong>{artifacts.length}</strong>
          <span>ARTIFACTS</span>
          <i />
          <strong>{duplicateCount}</strong>
          <span>DUPLICATE</span>
        </div>

        <button type="button" className="library-back" onClick={onClose}>
          <span>بازگشت</span>
          <svg viewBox="0 0 24 24" aria-hidden="true">
            <path d="M15 5 8 12l7 7" />
          </svg>
        </button>
      </header>

      <div className="library-toolbar">
        <label className="library-search">
          <svg viewBox="0 0 24 24" aria-hidden="true">
            <circle cx="11" cy="11" r="6" />
            <path d="m16 16 4 4" />
          </svg>
          <input
            value={search}
            onChange={(event) => setSearch(event.target.value)}
            placeholder="جستجو در کتابخانه..."
          />
        </label>

        <div className="library-filters">
          {(
            [
              ["all", "همه"],
              ["image", "تصاویر"],
              ["video", "ویدیو"],
              ["pdf", "PDF"],
              ["document", "اسناد"],
              ["audio", "صوت"],
              ["link", "لینک"],
              ["archive", "آرشیو"],
            ] as const
          ).map(([value, label]) => (
            <button
              key={value}
              type="button"
              className={
                filter === value
                  ? "library-filter library-filter-active"
                  : "library-filter"
              }
              onClick={() => setFilter(value)}
            >
              <span className="library-filter-icon" aria-hidden="true">
                {value === "all" ? (
                  <svg viewBox="0 0 24 24">
                    <rect x="4" y="4" width="6" height="6" rx="1.2" />
                    <rect x="14" y="4" width="6" height="6" rx="1.2" />
                    <rect x="4" y="14" width="6" height="6" rx="1.2" />
                    <rect x="14" y="14" width="6" height="6" rx="1.2" />
                  </svg>
                ) : (
                  <ArtifactIcon type={value as ArtifactType} />
                )}
              </span>

              <span className="library-filter-label">
                {label}
              </span>
            </button>
          ))}
        </div>

        <div className="library-toolbar-right">
          <label className="library-select-wrap">
            <span>SORT</span>
            <select
              value={sort}
              onChange={(event) => setSort(event.target.value as SortMode)}
            >
              <option value="newest">جدیدترین</option>
              <option value="oldest">قدیمی‌ترین</option>
              <option value="az">A → Z</option>
              <option value="za">Z → A</option>
              <option value="type">نوع</option>
              <option value="size">اندازه</option>
            </select>
          </label>

          <div className="library-view-toggle">
            <button
              type="button"
              className={viewMode === "compact" ? "active" : ""}
              onClick={() => setViewMode("compact")}
            >
              COMPACT
            </button>
            <button
              type="button"
              className={viewMode === "gallery" ? "active" : ""}
              onClick={() => setViewMode("gallery")}
            >
              GALLERY
            </button>
          </div>
        </div>
      </div>

      <div className="library-layout">
        <div className={`library-artifact-area library-artifact-area-${viewMode}`}>
          {groups.map((group) => (
            <section key={group.label} className="library-date-group">
              <header className="library-date-heading">
                <span>{group.label}</span>
                <i />
                <small>{group.items.length}</small>
              </header>

              <div className="library-artifact-list">
                {group.items.map((artifact) => (
                  <article
                    key={artifact.id}
                    className={`library-artifact-row library-artifact-${artifact.type} ${
                      selectedId === artifact.id ? "library-artifact-selected" : ""
                    }`}
                    tabIndex={0}
                    onClick={() => setSelectedId(artifact.id)}
                    onDoubleClick={() => mockOpen(artifact)}
                    onContextMenu={(event) => openContextMenu(event, artifact)}
                  >
                    <div className={`library-artifact-preview library-preview-${artifact.tone}`}>
                      <span className="library-preview-particles">
                        <i />
                        <i />
                        <i />
                        <i />
                      </span>
                      <ArtifactIcon type={artifact.type} />
                      <strong>{artifact.extension}</strong>
                    </div>

                    <div className="library-artifact-main">
                      {renamingId === artifact.id ? (
                        <input
                          ref={renameRef}
                          className="library-rename-input"
                          value={renameValue}
                          onChange={(event) => setRenameValue(event.target.value)}
                          onClick={(event) => event.stopPropagation()}
                          onBlur={commitRename}
                          onKeyDown={(event) => {
                            if (event.key === "Enter") commitRename();
                            if (event.key === "Escape") setRenamingId(null);
                          }}
                        />
                      ) : (
                        <button
                          type="button"
                          className="library-artifact-name"
                          title="برای Rename دوباره روی اسم کلیک کنید"
                          onClick={(event) => {
                            event.stopPropagation();

                            if (selectedId === artifact.id) {
                              beginRename(artifact);
                            } else {
                              setSelectedId(artifact.id);
                            }
                          }}
                        >
                          {artifact.name}
                        </button>
                      )}

                      <div className="library-artifact-meta-line">
                        <span>{artifact.extension}</span>
                        <i />
                        <span>{artifact.dateText}</span>
                        <i />
                        <span>{artifact.time}</span>
                      </div>

                      <div className="library-artifact-meta-line library-artifact-meta-secondary">
                        <span>{artifact.sizeText}</span>
                        <i />
                        <span>{artifact.source}</span>
                      </div>
                    </div>

                    <div className="library-artifact-status-zone">
                      <span
                        className={`library-artifact-status library-status-${artifact.status
                          .toLowerCase()
                          .replace(" ", "-")}`}
                      >
                        {artifact.status}
                      </span>
                      {artifact.status === "Duplicate" && <small>EXACT MATCH</small>}
                    </div>
                  </article>
                ))}
              </div>
            </section>
          ))}

          {filtered.length === 0 && (
            <div className="library-empty">
              <ArtifactIcon type="unknown" />
              <strong>موردی پیدا نشد</strong>
              <span>Filter یا Search را تغییر بده.</span>
            </div>
          )}
        </div>

        <aside className="library-detail-panel">
          {selected && (
            <>
              <div className={`library-detail-preview library-preview-${selected.tone}`}>
                <ArtifactIcon type={selected.type} />
                <strong>{selected.extension}</strong>
              </div>

              <div className="library-detail-title">
                <span>SELECTED ARTIFACT</span>
                <h2>{selected.name}</h2>
              </div>

              <dl className="library-detail-grid">
                <div>
                  <dt>TYPE</dt>
                  <dd>{selected.extension}</dd>
                </div>
                <div>
                  <dt>DATE</dt>
                  <dd>{selected.dateText}</dd>
                </div>
                <div>
                  <dt>TIME</dt>
                  <dd>{selected.time}</dd>
                </div>
                <div>
                  <dt>SIZE</dt>
                  <dd>{selected.sizeText}</dd>
                </div>
                <div className="wide">
                  <dt>SOURCE</dt>
                  <dd>{selected.source}</dd>
                </div>
                <div className="wide">
                  <dt>STATUS</dt>
                  <dd>{selected.status}</dd>
                </div>
                <div className="wide">
                  <dt>PATH / URL</dt>
                  <dd title={selected.pathOrUrl}>{selected.pathOrUrl}</dd>
                </div>
              </dl>

              {selected.status === "Duplicate" && (
                <div className="library-duplicate-panel">
                  <span>DUPLICATE DETECTED</span>
                  <strong>{selected.duplicateOf}</strong>
                  <p>نسخه نهایی با Hash محتوا Exact Duplicate را تشخیص می‌دهد.</p>
                </div>
              )}

              <div className="library-detail-actions">
                <button
                  type="button"
                  className="library-primary-action"
                  onClick={() => mockOpen(selected)}
                >
                  OPEN
                </button>
                <button type="button" onClick={() => beginRename(selected)}>
                  RENAME
                </button>
                <button type="button" onClick={() => showToast("Open folder — Prototype only")}>
                  OPEN FOLDER
                </button>
                <button
                  type="button"
                  onClick={() => showToast("Show in conversation — Prototype only")}
                >
                  SHOW IN CONVERSATION
                </button>
                <button type="button" onClick={() => showToast("Path copied — Prototype only")}>
                  COPY PATH
                </button>
              </div>

              <div className="library-danger-actions">
                <button type="button" onClick={() => removeArtifact(selected, false)}>
                  DELETE
                </button>
                <button type="button" onClick={() => removeArtifact(selected, true)}>
                  DELETE FOREVER
                </button>
              </div>
            </>
          )}
        </aside>
      </div>
      </div>

      {menu && (
        <div
          className="library-context-menu"
          style={{
            left: `${menu.x}px`,
            top: `${menu.y}px`,
          } as CSSProperties}
          onClick={(event) => event.stopPropagation()}
        >
          {(() => {
            const artifact = artifacts.find((item) => item.id === menu.artifactId);
            if (!artifact) return null;

            return (
              <>
                <button type="button" onClick={() => mockOpen(artifact)}>Open</button>
                <button type="button" onClick={() => showToast("Open folder — Prototype only")}>Open folder</button>
                <button type="button" onClick={() => beginRename(artifact)}>Rename</button>
                <button
                  type="button"
                  onClick={() => showToast(artifact.type === "link" ? "Link copied — Prototype only" : "Path copied — Prototype only")}
                >
                  {artifact.type === "link" ? "Copy link" : "Copy path"}
                </button>
                <button type="button" onClick={() => showToast("Show in conversation — Prototype only")}>Show in conversation</button>
                <span className="library-context-separator" />
                <button className="danger" type="button" onClick={() => removeArtifact(artifact, false)}>Delete</button>
                <button className="danger danger-strong" type="button" onClick={() => removeArtifact(artifact, true)}>Delete forever</button>
              </>
            );
          })()}
        </div>
      )}

      {toast && <div className="library-toast">{toast}</div>}
    </section>
  );
}

export default LibraryView;
